version: "3.8"

volumes:
  db: {}

services:

  tg_bot:
    build: .
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=13781001
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tg_vozd
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5439:5432
