version: "2"

volumes:
  db: {}

services:

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=13781001
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tg_vozd
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5435

  tg_bot:
    build: .
    restart: always

